#!/bin/sh

cargo build

exe_file="../../target/debug/minesweeper"

echo $exe_file

# generate directory with test cases 
rm -rf tests
mkdir tests
cd tests
cp ../test_files/*.mines .
cp ../test_files/*.expected .
cp ../test_files/*.error .

code=0

# run all tests
for file in *.mines ; do 
   echo "Run test $file"
   output_file="${file%.*}.out"
   expected_result_file="${file%.*}.expected"
   $exe_file $file
   diff $expected_result_file $output_file
   if [[ $? -ne 0 ]]; then
      echo "$(tput setaf 1)test failed$(tput sgr0)"
      code=1
   else
      echo "$(tput setaf 2)test OK$(tput sgr0)"
   fi
done 

for file in *.error ; do 
   echo "Run test $file"
   $exe_file $file
   if [[ $? -eq 0 ]]; then
      echo "$(tput setaf 1)test failed$(tput sgr0)"
      code=1
   else
      echo "$(tput setaf 2)test OK$(tput sgr0)"
   fi

done

exit $code

